### ISSUE TITLE
[Bug-Underhaul] Calculation Mismatch

### ISSUE THREAD

**Issue by ThePoleThatFishes** [Kurtchekov/TurbineCalculator#4] opened 2020-08-14 21:52 UTC
I have found a bug in Underhaul calculator, RF/mB is lower in the calculator than in-game. (Coil Conductivities have been set to 100% to not skew RF/t generation, the turbine is running the custom 3 RF/mb, 250% expansion fuel -thanks for implementing!)
Overhaul calculator works fine, the RF/mB values match in-game and in the calculator.
![bugreport](https://user-images.githubusercontent.com/63863162/90295202-fed12e00-de90-11ea-8500-83e5425ed9b8.png)

**Comment by Kurtchekov** [comment] 2020-08-15 00:08
Hmm, might be caused by slightly different values for each kind of blade. Can you compare those for me, please?

**Comment by ThePoleThatFishes** [comment] 2020-08-15 09:56
The configuration for each blade is the same as in-game, Steel 100% efficiency, 140% expansion, Extreme 110% efficiency, 160% expansion, SiC 125% efficiency, 180% expansion and Stator 75% expansion. I had the same discrepancy even when I used 108% efficiency Extreme in-game and in the calculator. 

I also took a look at Tom's code for the underhaul turbines and made a small python script based on that, for calculating the expansion levels, if that helps
[TurbineCalculator.zip](https://github.com/Kurtchekov/TurbineCalculator/files/5078451/TurbineCalculator.zip)

**Comment by Kurtchekov** [comment] 2020-08-16 00:04
Should be fixed by now! Thanks a LOT for the report, screenshot and that python script! It was much easier to fix the problem with those in hand ^^

**Closed** 2020-08-16 00:04 UTC
